Upgrade lodash to 4.17.21
oat-sa/tao-core-libs-fe pull request #112
Opened 2023-09-27 10:47 UTC by yukipastelcat

Ticket: https://oat-sa.atlassian.net/browse/ADF-1391

## What's Changed

- [lodash](https://www.npmjs.com/package/lodash) dependency been upgraded to 4.17.21 w/o locking the version
- Upgrade has been done with `--lockfile-version 1` flag to avoid changing lockfile structure
- `_.contains` has been replaced with `_.includes` as it was changed in [3.10.1](https://lodash.com/docs/3.10.1#includes) and alias was removed in [4.17.21](https://lodash.com/docs/4.17.15#includes)

## How to test
- Run `npm run build` in order to check that build isn't broken
- Run `npm test` to check qunit-testrunner tests

2023-09-27 12:55 UTC, ViktoriaKh-oat approved these changes
Looks good! Thanks!
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic

2023-09-27 13:20 UTC, btamas requested changes
This is a breaking change.

2023-09-28 08:33 UTC, yukipastelcat commented
@btamas why? This is not breaking the API of the package, it remains unchanged, behaviour of the methods is also unchanged

2023-09-28 10:58 UTC, btamas approved these changes

2023-09-28 10:58 UTC, btamas commented
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [ ] Pull request's target is not `master`
- [ ] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Commits messages are meaningful
- [ ] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2023-09-28 11:58 UTC, merged

2023-09-29 06:07 UTC, jsconan commented on package.json
> +        "lodash": "^4.17.21",
**issue:** Freaking! Did you check if other libs were aligned with this before merging? :o

2023-09-29 10:48 UTC, btamas commented on package.json
> +        "lodash": "^4.17.21",
I've checked and there are only ~10 `_.` calls, like defer, forIn or extend. All of them exists in the new version.